Vagrant.configure(2) do |config|

  config.vm.define "acs" do |acs|
    acs.vm.synced_folder ".", "/vagrant", disabled: true
    acs.vm.box = "ubuntu/xenial64"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.33.10"
    acs.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 1
    end
  end
end
